title: DeFiNido
email: "unotrd@gmail.com"
description: Pagina oficial de @nidodefi
url: "https://definido.link"
twitter: nidodefi

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
